# Generated by Django 2.2.4 on 2019-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191209_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='peraon_no',
        ),
        migrations.AddField(
            model_name='client',
            name='no_of_person',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
